CREATE TABLE IF NOT EXISTS users (
    userid VARCHAR(36) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    taskid BIGSERIAL PRIMARY KEY, -
    title VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL,
    user_id VARCHAR(36) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(userid) ON DELETE CASCADE
);
